// src/components/lastmonth.vue
<template>
  <div id="last_month_summary">
    <div>
      <div>{{ summaryTitle }}</div>
      <div v-html="tableHeader"></div>
      <div v-html="averageHighData"></div>
      <div v-html="averageLowData"></div>
      <div v-html="precipData"></div>
      <br />
      <!-- this is normally pos in records -->
      <div v-html="warmestTempData"></div>
      <div v-html="coldestTempData"></div>
    </div>
  </div>
</template>

<script>
import stringmixin from "../mixins/stringpad.mixin";
import { format, isValid } from "date-fns";

export default {
  name: "last-month",
  mixins: [stringmixin],
  props: {
    lastMonth: {
      type: Object,
      default: () => {
        return {};
      },
    },
    city: String,
  },

  computed: {
    summaryTitle() {
      return `Weather Statistics for ${this.lastMonth.month || ""}`;
    },

    tableHeader() {
      return `&nbsp;${this.padString(this.city, 11, false)}&nbsp;This Year&nbsp;&nbsp;Normal`;
    },

    averageHighData() {
      return `${this.padString("Average High", 15, false)}${this.padString(
        this.lastMonth?.actual?.averageHigh || "N/A",
        5,
        true
      )}&nbsp;&nbsp;&nbsp;&nbsp;${this.padString(this.lastMonth?.normal?.normalHigh || "N/A", 5, true)}`;
    },

    averageLowData() {
      return `${this.padString("Average Low", 15, false)}${this.padString(
        this.lastMonth?.actual?.averageLow || "N/A",
        5,
        true
      )}&nbsp;&nbsp;&nbsp;&nbsp;${this.padString(this.lastMonth?.normal?.normalLow || "N/A", 5, true)}`;
    },

    precipData() {
      // TODO: handle is winter
      return `${this.padString("Precip (MM)", 15, false)}${this.padString(
        this.lastMonth?.actual?.totalPrecip || "N/A",
        5,
        true
      )}&nbsp;&nbsp;&nbsp;&nbsp;${this.padString(this.lastMonth?.normal?.normalPrecip || "N/A", 5, true)}`;
    },

    warmestDayTemp() {
      const temp = this.lastMonth?.actual?.warmestDay?.temp;
      if (temp === undefined) return null;
      return `${temp > 0 ? "+" : "-"}${temp.toFixed(1)}`;
    },

    warmestTempData() {
      return `${this.padString("Warmest Temp.", 14, false)}${this.padString(
        this.warmestDayTemp || "N/A",
        5,
        true
      )}&nbsp;ON THE ${this.getDateNumberSuffix(this.lastMonth?.actual?.warmestDay?.day)}.`;
    },

    coldestDayTemp() {
      const temp = this.lastMonth?.actual?.coldestDay?.temp;
      if (temp === undefined) return null;
      return `${temp > 0 ? "+" : "-"}${temp.toFixed(1)}`;
    },

    coldestTempData() {
      return `${this.padString("Coldest Temp.", 14, false)}${this.padString(
        this.coldestDayTemp || "N/A",
        5,
        true
      )}&nbsp;ON THE ${this.getDateNumberSuffix(this.lastMonth?.actual?.coldestDay?.day)}`;
    },
  },

  methods: {
    getDateNumberSuffix(number) {
      // this is a really hacky way of getting 1st, 2nd, 3rd, etc..
      number = parseInt(number);
      const date = new Date();
      date.setDate(number);
      if (!isValid(date)) return number;

      return this.padString(format(date, "do"), 4, true);
    },
  },
};
</script>

<style lang="scss" scoped>
#last_month_summary {
  align-items: center;
  display: flex;
  flex-direction: column;
  width: 100%;
}
</style>

// src/display/components/screens/lastmonth.tsx
import { format, isValid, subMonths } from "date-fns";
import { useEffect } from "react";
import { LastMonth } from "types";
import { AutomaticScreenProps } from "types/screen.types";

type LastMonthScreenProps = {
  city: string;
  lastMonth: LastMonth;
} & AutomaticScreenProps;

export function LastMonthScreen(props: LastMonthScreenProps) {
  const { city, lastMonth, onComplete } = props ?? {};

  useEffect(() => {
    // if there's no data just return
    if (!city?.length || !lastMonth?.actual || !lastMonth?.normal) onComplete();
  }, []);

  if (!city?.length || !lastMonth?.actual || !lastMonth?.normal) return <></>;

  const month = format(subMonths(new Date(), 1), "MMMM");
  const formatNumber = (value: number) => (value !== undefined ? value.toFixed(1).toString().padStart(5) : "N/A");
  const formatTemp = (value: number) =>
    value !== undefined ? ((value > 0 ? "+" : "") + value.toFixed(1).toString()).padStart(5) : "N/A";
  const formatDayWithSuffix = (value: number) => {
    const date = subMonths(new Date(), 1);
    date.setDate(value);
    if (!isValid(date)) return value ?? "N/A";

    return format(date, "do").padStart(4);
  };

  return (
    <div id="lastmonth_screen">
      <div>Weather Statistics for {month}</div>
      <div>
        &nbsp;{city.slice(0, 11).padEnd(11)}&nbsp;This Year{"".padStart(2)}Normal
      </div>
      <div>
        {"Average High".padEnd(15)}
        {formatNumber(lastMonth.actual?.averageHigh)}
        {"".padStart(4)}
        {formatNumber(lastMonth.normal?.temperature.max)}
      </div>
      <div>
        {"Average Low".padEnd(15)}
        {formatNumber(lastMonth.actual?.averageLow)}
        {"".padStart(4)}
        {formatNumber(lastMonth.normal?.temperature.min)}
      </div>
      <div>
        {"Precip (MM)".padEnd(15)}
        {formatNumber(lastMonth.actual?.totalPrecip)}
        {"".padStart(4)}
        {formatNumber(lastMonth.normal?.precip.amount)}
      </div>
      <br />
      {/* on the original channel this line mentioned where in records the precip amount came (1st, 3rd, 9th, etc.)*/}
      <div>
        {"Warmest Temp.".padEnd(14)}
        {formatTemp(lastMonth.actual?.warmestDay.value)} on the {formatDayWithSuffix(lastMonth.actual?.warmestDay.day)}
      </div>
      <div>
        {"Coldest Temp.".padEnd(14)}
        {formatTemp(lastMonth.actual?.coldestDay.value)} on the {formatDayWithSuffix(lastMonth.actual?.coldestDay.day)}
      </div>
    </div>
  );
}
